# Generated by Django 4.0.1 on 2022-02-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0003_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
