# Generated by Django 4.0.1 on 2022-03-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='driver',
        ),
    ]
