# Generated by Django 4.0.1 on 2022-03-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0010_rename_user_profile_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car',
            field=models.CharField(default='Car', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Email', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='subie.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modifications',
            field=models.TextField(default='Mods'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
    ]
