# Generated by Django 4.0.1 on 2022-03-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0011_alter_profile_car_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
